src/Entity/Website.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[ORM\Table(name: '`website`')]
#[UniqueEntity(fields: ['name', 'domain'], message: 'There is already a site with one of these credentials!')]
class Website
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $files_path = null;

    #[ORM\Column(length: 255)]
    private ?string $domain = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFilesPath(): ?string
    {
        return $this->files_path;
    }

    public function setFilesPath(string $files_path): self
    {
        $this->files_path = $files_path;

        return $this;
    }

    public function getDomain(): ?string
    {
        return $this->domain;
    }

    public function setDomain(string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Website;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('domain')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/Admin/CategoryController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Website;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class CategoryController extends AbstractCrudController
{

    public static function getEntityFqcn(): string
    {
        return Website::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Website')
            ->setEntityLabelInPlural('Websites');
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new("id")->hideOnForm(),
            TextField::new("name"),
            TextField::new("domain"),
            TextField::new("files_path")->setDisabled(true)->hideWhenCreating()
        ];
    }

    public function createEntity(string $entityFqcn)
    {
        $entity = new $entityFqcn();
        $entity->setFilesPath("/var/www/" . $entity->getName());
        return $entity;
    }

    /*#[Route('/', name: 'app_category_index', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_category_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CategoryRepository $categoryRepository): Response
    {
        $category = new Category();
        if ($request->getMethod() == "POST") {
            $path = "/var/www/" . strtolower(str_replace(" ", "_", $request->get("name")));
            $category->setName($request->get("name"));
            $category->setFilesPath($path);
            $category->setDomain($request->get("domain"));

            $categoryRepository->add($category, true);

            shell_exec("cd ~ && mkdir /var/www/" . strtolower(str_replace(" ", "_", $request->get("name"))));
            shell_exec("sh " . PATH . "/install_site.sh " . $path . " " . $request->get("domain"));

            return $this->redirect('/dashboard?menuIndex=2&routeName=app_category_index&submenuIndex=-1');
        }

        return $this->render('category/new.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/{id}', name: 'app_category_show', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('category/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $categoryRepository->remove($category, true);
        }

        return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
    }*/
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/category/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
    <h1>Edit Category</h1>

    {{ include('category/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_category_index') }}">back to list</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}

templates/category/index.html.twig
{% extends '@!EasyAdmin/crud/index.html.twig' %}

{#% extends '@!EasyAdmin/layout.html.twig' %}

{% block content %}
    {% block content_header %}
        <h1>Websites</h1>
        <br>
    {% endblock %}
    <br>
    <a href="/dashboard?menuIndex=2&routeName=app_category_new&submenuIndex=-1"><span class="fa fa-plus"></span> Add Site</a>
    <br>

    {% block main %}
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Files Path</th>
                    <th>Domain</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.filesPath }}</td>
                    <td>{{ category.domain }}</td>
                    <td>
                        <a href="{{ path('app_category_show', {'id': category.id}) }}">Show</a>
                        <a href="{{ path('app_category_edit', {'id': category.id}) }}">Edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">No records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endblock %}

{% endblock %#}

templates/category/new.html.twig
{% extends '@!EasyAdmin/layout.html.twig' %}

{% block title %}New Category{% endblock %}

{% block content %}
    {% block content_header %}
        <h1>Add Site</h1>
        <br>
    {% endblock %}

    <form method="POST" action="/dashboard?menuIndex=2&routeName=app_category_new&submenuIndex=-1">
        <label for="name">Name</label>
        <br>
        <input type="text" name="name" id="name" style="width: 20em;" placeholder="Name" />
        <br>
        <br>
        <label for="domain">Domain</label>
        <br>
        <input type="text" name="domain" id="domain" style="width: 20em;" placeholder="Domain" />
        <br>

        <br>
        <br>
        <button name="btn" class="btn">{{ button_label|default('Save') }}</button>
        <br>
    </form>

    <br>
    <a href="{{ path('app_category_index') }}">Back to list</a>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category{% endblock %}

{% block body %}
    <h1>Category</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ category.name }}</td>
            </tr>
            <tr>
                <th>Files_path</th>
                <td>{{ category.filesPath }}</td>
            </tr>
            <tr>
                <th>Domain</th>
                <td>{{ category.domain }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_category_index') }}">back to list</a>

    <a href="{{ path('app_category_edit', {'id': category.id}) }}">edit</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}